export const COMPETITION = {
    LOAD: 'COMPETITION_LOAD',
    GET_ONE_COMPETITION: 'GET_ONE_COMPETITION',
    RESET_COMPETITION: 'RESET_COMPETITION',
    RESET_ERROR: 'RESET_ERROR'
}

export const AUTH = {
    USER_LOAD: 'USER_LOAD',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGOUT: 'LOGOUT'
}