export const COMPETITION = {
    LOAD: 'COMPETITION_LOAD',
    LOAD_SUCCESS: 'COMPETITION_LOAD_SUCCESS',
    LOAD_FAIL: 'COMPETITION_LOAD_FAIL',
    GET_ONE_COMPETITION: 'GET_ONE_COMPETITION',
    GET_ONE_COMPETITION_SUCCESS: 'GET_ONE_COMPETITION_SUCCESS',
    GET_ONE_COMPETITION_FAIL: 'GET_ONE_COMPETITION_FAIL',
    RESET: 'RESET',
    RESET_SUCCESS: 'RESET_SUCCESS'
}